[project]
name = "fv-ai-codegen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deal>=4.24.4",
    "numpy>=2.2.3",
]
